/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PUB_SUB_DELIV_H_RPCGEN
#define _PUB_SUB_DELIV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define POSTMESLEN 192

typedef char *postmessage;

#define PUBSUBCLTPROG 0x20000012
#define PUBSUBCLTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define deliver 1
extern  void * deliver_1(postmessage *, CLIENT *);
extern  void * deliver_1_svc(postmessage *, struct svc_req *);
extern int pubsubcltprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define deliver 1
extern  void * deliver_1();
extern  void * deliver_1_svc();
extern int pubsubcltprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_postmessage (XDR *, postmessage*);

#else /* K&R C */
extern bool_t xdr_postmessage ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PUB_SUB_DELIV_H_RPCGEN */
