/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pub_sub.h"

bool_t
xdr_topic (XDR *xdrs, topic *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TOPLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MESLEN))
		 return FALSE;
	return TRUE;
}
