/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pub_sub.h"

bool_t
xdr_topic (XDR *xdrs, topic *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TOPLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MESLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hashstring (XDR *xdrs, hashstring *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, HASHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, USERLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sessionid (XDR *xdrs, sessionid *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_argument (XDR *xdrs, argument *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->topic_or_message))
		 return FALSE;
	switch (objp->topic_or_message) {
	case 0:
		 if (!xdr_topic (xdrs, &objp->argument_u.t))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_message (xdrs, &objp->argument_u.m))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_param (XDR *xdrs, param *objp)
{
	register int32_t *buf;

	 if (!xdr_sessionid (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_argument (xdrs, &objp->arg))
		 return FALSE;
	 if (!xdr_hashstring (xdrs, &objp->hash))
		 return FALSE;
	return TRUE;
}
