/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PUB_SUB_H_RPCGEN
#define _PUB_SUB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TOPLEN 64
#define MESLEN 128

typedef char *topic;

typedef char *message;

#define PUBSUBPROG 0x20000011
#define PUBSUBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define set_channel 1
extern  short * set_channel_1(topic *, CLIENT *);
extern  short * set_channel_1_svc(topic *, struct svc_req *);
#define subscribe 2
extern  short * subscribe_1(void *, CLIENT *);
extern  short * subscribe_1_svc(void *, struct svc_req *);
#define unsubscribe 3
extern  short * unsubscribe_1(void *, CLIENT *);
extern  short * unsubscribe_1_svc(void *, struct svc_req *);
#define publish 4
extern  short * publish_1(message *, CLIENT *);
extern  short * publish_1_svc(message *, struct svc_req *);
extern int pubsubprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define set_channel 1
extern  short * set_channel_1();
extern  short * set_channel_1_svc();
#define subscribe 2
extern  short * subscribe_1();
extern  short * subscribe_1_svc();
#define unsubscribe 3
extern  short * unsubscribe_1();
extern  short * unsubscribe_1_svc();
#define publish 4
extern  short * publish_1();
extern  short * publish_1_svc();
extern int pubsubprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_topic (XDR *, topic*);
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_topic ();
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PUB_SUB_H_RPCGEN */
